### ISSUE TITLE
sphinx 6.x is much more of a slow memory hog than 5.3, investigate

### ISSUE THREAD

**Issue by zzzeek** [sqlalchemyorg/zzzeeksphinx#20]
assuming they've just built more bloat in, we will have to upgrade ln6 or change our build system

**Comment by zzzeek** [comment]
im trying to do a build on ln6 , which is a slow process regadless, to see if we can get past the big memory hump that happens after "preparing documents"

**Comment by zzzeek** [comment]
https://github.com/sphinx-doc/sphinx/issues/11352

looks like this new sphinx will cost me another $20 a month for bigger linode, unless I want to change where the docs are built (Which i dont)

**Comment by CaselIT** [comment]
Maybe we can use GitHub actions for the build?

The machines they use are not great, but they should be able to build the docs

**Comment by zzzeek** [comment]
OK how do we get the files from the action machine to the web host?

**Comment by zzzeek** [comment]
i mean yeah that would be great

**Comment by CaselIT** [comment]
I guess we can either have the GitHub machine push them to the host (using ssh or ftp or similar), or maybe make the action create an artifact and then the machine could download it?

I would have to look to see if maybe there is an url to get the "last artifact with name x" so that the hosting could just check the url in polling or something

**Comment by zzzeek** [comment]
> I guess we can either have the GitHub machine push them to the host (using ssh or ftp or similar), or maybe make the action create an artifact and then the machine could download it?

yeah we dont want the GH action machine with access to the webhost.  i know there are secrets and things but the machine itself would have access which seems like a bad idea.    so yes artifact download.  we can make a cron on the webhost that just looks for it.    i mean i can do this anyway with the ci3 machine maybe but if there's an action artfaact place that's just public, that's even easier.

**Comment by CaselIT** [comment]
Seems guthub has a cli we can use https://cli.github.com/manual/gh_run

I think we can do this:
- `gh run list` - the the last workflow run
- check if we already have it, if so don't do anything
- `gh run download` - download the new files

I can try writing something to have an action build the docs and the script to download il

**Comment by zzzeek** [comment]
the build is failing even on ci3 machine, which is a linode 2 cpu + 4g ram.  so....this is bad

**Comment by CaselIT** [comment]
seems a bug on sphinx side if on v5 all was fine on 1cpu and 1gb or ram (or 2?) and now we can't build on 2 cpu and 4gb.

**Comment by zzzeek** [comment]
right but I can' t stop them from constantly doing this, they keep refactoring their code when I wish they would just stop

**Comment by CaselIT** [comment]
ok, this is a script that can be run in cron to download the last artifact run from github and copied to the public folder.
```bash
#!/bin/bash -e
branch=workflow_test_doc_build  # change with wanted branch
dest_folder=/public/docs  # change with public docs folder
current_run_file=/home/sa_current_run  # keep track of the last deployed version

last_run=$(gh run list --workflow 'Build docs' --branch $branch --limit 1 --status success --json databaseId | jq -r .[0].databaseId | tr -d '\r')
echo "Last run is '$last_run'"

touch $current_run_file
current_run=$(cat $current_run_file)

if [ "$current_run" == "$last_run" ]
then
    echo "Last build already deployed. Nothing to do"
    exit 0
else
    echo "Downloading updated file"
    gh run download $last_run --name docs-archive --dir /tmp
    cd /tmp
    tar zxf docs.tgz
    mv doc/build/output/html/* $dest_folder
    echo $last_run > $current_run_file
    echo "Done. Updated $dest_folder with run $last_run"
fi
```

requires gh (the github cli) to be installed and configured (it requires a login) and jq.

in what repo would the be placed?

**Comment by CaselIT** [comment]
btw I've just tried building with sphix v6 on github and all seems ok: https://github.com/sqlalchemy/sqlalchemy/actions/runs/4780267329/jobs/8497903161

**Comment by zzzeek** [comment]
> btw I've just tried building with sphix v6 on github and all seems ok: https://github.com/sqlalchemy/sqlalchemy/actions/runs/4780267329/jobs/8497903161

that was **JUST RELEASED** 25 minutes ago !!

**Comment by CaselIT** [comment]
oh it ran 6.2.0

**Comment by zzzeek** [comment]
THEY FIXED IT!!

**Comment by CaselIT** [comment]
oh cool.

well since we already have the workflow and the download script do you want to switch?

**Comment by zzzeek** [comment]
I dont know , I have to go out w/ my parents now.   i want to try this on ln6 just to see what happens but yes, ln6 is too small for sphinx anyway we sohudl still use this.

**Comment by zzzeek** [comment]
likely https://github.com/sphinx-doc/sphinx/pull/11192

**Comment by CaselIT** [comment]
not really urgent.

I guess we can try things out. We already have a couple of artifacts so we can try to see if the script works on the server machine, then we can decide what to do

**Comment by CaselIT** [comment]
btw I guess we this can be closed and continue discussion on the new build here https://github.com/sqlalchemy/sqlalchemy/pull/9695

**Comment by zzzeek** [comment]
we still can't move to 6.2 on the ln6 machine without me spending more money, as the machine now runs out of space

https://github.com/sphinx-doc/sphinx/issues/11354


now the machine has only 6g of space, I should likely grow it anyway
